### ISSUE TITLE
Gluon wrapper

### ISSUE THREAD

**Issue by deepakkumar1984** [takuya-takeuchi/MXNetDotNet#1]
Hello,

Thanks for the great work! Are you planning to release gluon wrapper as well?

**Comment by takuya-takeuchi** [comment]
I don't know about Gluon well.

But it seems like to provide only one file as exported C++ API?
https://github.com/gluon-api/gluon-api/blob/master/docs/gluon_api.h

However, there is no examples, no source and no binary. So I will not test whether wrapper works well after implements.
And if there is only python codes, I will not create wrapper.

**Comment by deepakkumar1984** [comment]
Closing this issue since i will use ndarray and symbol
