### ISSUE TITLE
How to extract values from ndarray

### ISSUE THREAD

**Issue by deepakkumar1984** [takuya-takeuchi/MXNetDotNet#2]
I tried using GetData method of NDArray but it return array of pointers. How to get the values out of it. Please advise?

**Comment by takuya-takeuchi** [comment]
You could use SyncCopyToCPU method.

**Comment by deepakkumar1984** [comment]
Even I tried it but still copy the pointers.

**Comment by takuya-takeuchi** [comment]
You must manipulate pointer.
Please refer NDArray.ToString implementation.

**Comment by deepakkumar1984** [comment]
![image](https://user-images.githubusercontent.com/6328361/49323820-a13c6700-f571-11e8-9630-eeecb6dfa464.png)

Tried with ToString(), but still getting pointers. Not sure what could be missing.
