### ISSUE TITLE
Hello, I am interested in using this software.  Is it still maintained and how are is interop code created? Typed manually, or is an extraction tool used. Looking forward to a reply.

### ISSUE THREAD

**Issue by Bumblebee1964** [takuya-takeuchi/MXNetDotNet#3]
# Summary of your issue
Hello, I am interested in using this software. Just a few questions: Is it still maintained and how is the interop code created? Typed manually, or is an extraction tool used?  Looking forward to a reply.
# Environment

Write your environment.
Windows 10

# What did you do when you faced the problem?

//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by takuya-takeuchi** [comment]
Interop op code is typed by manually
I know that is penance.

Op code of TensorflowSharp and TorchSharp are generated automatically.
So I want to imitate these aproach.

**Comment by Bumblebee1964** [comment]
Hi Takuya,

Thanks for your response. From your answer I derive that you are still engaged?

I will see if I can use it in my project and if so, contribute to it if I need extensions.

Best regards
Fred

**Comment by takuya-takeuchi** [comment]
Thank you for interest in mxnetdotnet.
Yes, I will develop and contribute it.

but I have many task which take my developpment time.
I may not be able to satisfy your requirements.

I must catch up latest mxnet code firstfirst and foremost.

**Comment by advancedwebdeveloper** [comment]
@takuya-takeuchi , are you interested to cooperate with contributors of https://scisharp.github.io/SciSharp/ ? Microsoft moving away from TensorflowSharp and will follow the development of https://github.com/SciSharp/Torch.NET.

**Comment by takuya-takeuchi** [comment]
Now, I develop libtorch wrapper.
I am interested in your project but I have no time to contribute.
